name: test
on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      # Caching
      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}-14.x

      - uses: bahmutov/npm-install@v1.1.0
      - name: Build files
        run: yarn run build
      - name: Run tests
        run: yarn run test
      - name: Run benchmark
        run: yarn run benchmark
